name: backup to github.com
on:
  push:
    branches:
      - main
env:
  KEY: "./sshkey"

jobs:
  push-github:
    runs-on: self-hosted
    env:
      BRANCH: "HEAD:refs/heads/main"
      GIT_SSH_COMMAND: "ssh -i $KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    steps:
      - uses: actions/checkout@v4
        env:
          GIT_SSL_NO_VERIFY: true
        with:
          clean: true
          set-safe-directory: true
          fetch-depth: 0
      - name: setup ssh key
        run: |
          echo "${{ secrets.SSH_PRIVATEKEY_GITHUB }}" | tr -d '\r' > $KEY
          chmod 600 $KEY
      - name: push to github.com
        id: normal_push
        env:
          GIT_SSH_COMMAND: "ssh -i $KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        run: |
          git remote remove github || true
          git remote add github git@github.com:s-ymgch228/helix.git
          git push github $BRANCH
      - name: force push
        if: failure() && steps.normal_push.outcome == 'failure'
        run: |
          export TZ="Asia/Tokyo"
          TAG_NAME="$(date +'%Y%m%d-%H%M%S')"

          git config user.name "gitea-actions"
          git config user.email "gitea-actions@noreply.example.jp"

          git fetch github
          git tag $TAG_NAME github/main
          git push github $TAG_NAME
          git push github $BRANCH --force
      - name: cleanup
        if: always()
        run: rm -f $KEY
